version: "2.1"

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./htdocs:/var/www/html
    depends_on:
      - php

  php:
    build: ./php
    volumes:
      - ./htdocs:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql
    platform: linux/arm64/v8
    container_name: mysql
    user: "1000:50"
    ports:
      - "3306:3306"
    volumes:
    - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rookt
    command: --innodb-use-native-aio=0

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=rookt
    links:
      - mysql
    ports:
      - 8080:80
    volumes:
      - ./phpmyadmin/sessions:/sessions

volumes:
  db-data:
